# Generated by Django 2.1.3 on 2019-01-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprints',
            fields=[
                ('bpID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bpName', models.CharField(max_length=100)),
            ],
        ),
    ]
