# Generated by Django 2.1.3 on 2019-01-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blueprints',
            new_name='Building',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='bpID',
            new_name='buildID',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='bpName',
            new_name='buildName',
        ),
    ]
